export const pitch2 = {
  today: {
    eyebrow: "After hours today",
    headline: "Most after hours teams are still reactive.",
    lines: [
      "Most of the night is spent checking loads that are already moving.",
      "And too often, the first sign of a real problem is an angry broker calling to ask:",
    ],
    quote: "Where is my truck?",
    late: "By that point, the load is already late.",
    hit: "And the customer relationship already took a hit.",
    emotion: "We found out too late.",
    incoming: "Incoming call",
    broker: "Broker",
    bubble: "My delivery was at 8 PM. Where is the truck?",
    operator: "Ana, After Hours Agent",
    operatorLine: "Opening ELD… checking T-1042",
  },
  workflow: {
    eyebrow: "What actually happens all night",
    headline: "Doing after hours properly takes a lot of manual work.",
    steps: [
      { number: "01", title: "Check the truck", text: "Open the ELD or GPS portal. Find the current truck location." },
      { number: "02", title: "Check the next stop", text: "Find the pickup or delivery appointment." },
      { number: "03", title: "Calculate the ETA", text: "Take the truck location. Open Google Maps. Compare the route time with the appointment." },
      { number: "04", title: "Call the driver", text: "If the truck looks late, call the driver. Ask what happened. Ask when they will arrive." },
      { number: "05", title: "Update everyone", text: "Write down the new ETA. Update the system. Tell dispatch or the broker if needed." },
    ],
    chain: ["ELD", "Location", "Google Maps", "Appointment", "Phone", "Update"],
    queue: "Next truck in queue",
    footer: "And you have to do this for every active truck.",
  },
  language: {
    eyebrow: "Another problem",
    headline: "Then you still have to reach the driver.",
    lines: [
      "Sometimes they answer.",
      "Sometimes they don’t.",
      "And sometimes they don’t speak the same language as your after hours team.",
    ],
    drivers: [
      { id: "T-1042", name: "M. Johnson", lang: "English" },
      { id: "T-2187", name: "J. Rivera", lang: "Spanish" },
      { id: "T-3301", name: "N. Petrović", lang: "Serbian" },
    ],
    operator: "One operator. Three languages.",
    line: "Language should not be the reason you cannot get an ETA.",
    tease: "What if all of this happened automatically?",
  },
  cost: {
    eyebrow: "The real problem",
    headline: "After hours feels like a cost center.",
    lines: [
      "You pay people to watch loads.",
      "Check GPS.",
      "Make check calls.",
      "Update ETAs.",
      "React to problems.",
    ],
    but: "But most of that work does not move another truck or book another load.",
    payoff: "Your night team is maintaining freight instead of moving more freight.",
    timeLabel: "Time spent tonight",
    timeItems: ["Tracking", "Check calls", "GPS checks", "Updates"],
    bookedLabel: "New loads booked",
    bookedValue: "0",
    tease: "That is what Zonik changes.",
  },
  idea: {
    eyebrow: "With Zonik",
    headline: "Zonik takes the tracking work off their plate.",
    points: [
      "Zonik watches every active load.",
      "It catches delays.",
      "It calls drivers when something looks wrong.",
      "It gets the reason and the new ETA.",
      "And it only brings your team in when a human is actually needed.",
    ],
    payoff: "Your after hours team can start working like a third shift dispatch team.",
    zonikLine: "Zonik handles monitoring.",
    teamLine: "Your people handle exceptions and book freight.",
    beforeLabel: "Before",
    operatorLabel: "Your operator",
    zonikLabel: "Zonik",
    teamLabel: "Your team",
    beforeTasks: ["GPS", "Google Maps", "Phone calls", "ETA updates"],
    afterZonik: ["Monitor loads", "Catch delays", "Call drivers", "Update ETAs"],
    afterTeam: ["Book load", "Cover truck", "Talk to broker", "Solve exception"],
  },
  how: {
    eyebrow: "How it works",
    headline: "How Zonik works",
    sub: "Four things. All night.",
    steps: [
      {
        number: "01",
        title: "Connect",
        headline: "Connect your load and GPS data.",
        text: "Zonik gets your active loads, trucks, drivers, stops and live location.",
        visual: "TMS + ELD into Zonik",
      },
      {
        number: "02",
        title: "Monitor",
        headline: "Zonik watches every active load.",
        text: "Every truck. Every next stop. Every live ETA. All night.",
      },
      {
        number: "03",
        title: "Act",
        headline: "Something looks wrong? Zonik makes the call.",
        text: "Zonik calls the driver, asks what happened and gets the latest ETA.",
        langs: ["English", "Spanish", "Serbian"],
      },
      {
        number: "04",
        title: "Escalate",
        headline: "Your team only steps in when needed.",
        text: "If Zonik cannot handle the situation, it sends your team the full context.",
      },
    ],
    statuses: ["On time", "At risk", "Delayed", "GPS offline"],
    escalate: [
      "Problem detected",
      "Driver called",
      "Reason + ETA collected",
      "Resolved by Zonik",
      "Human needed",
    ],
  },
  loadOnTime: {
    eyebrow: "Load #48291, T-1042",
    headline: "Everything looks fine.",
    sub: "Zonik keeps watching. Your team does not need to do anything. If the load is healthy, Zonik simply monitors it.",
    nextStop: "Chicago, IL",
    scheduled: "Scheduled",
    liveEta: "Live ETA",
    status: "On time",
  },
  loadDelay: {
    eyebrow: "Load #48291, T-1042",
    headline: "Now something changed.",
    sub: "Zonik sees the problem automatically. No one had to notice it first.",
    scheduled: "Scheduled",
    liveEta: "Live ETA",
    late: "45 min late",
    risk: "Appointment at risk",
    status: "At risk",
    call: "Call triggered",
  },
  loadCall: {
    eyebrow: "Load #48291, T-1042",
    headline: "Zonik calls the driver.",
    language: "Language: English",
    zonik: "Zonik",
    line: "Hi, I’m checking Load #48291. Are you still on schedule for Chicago?",
    driver: "Driver, T-1042",
    reply: "Truck broke down on I-70. New ETA should be around 20:45.",
    extract: {
      reason: "Reason",
      reasonVal: "Breakdown",
      eta: "New ETA",
      etaVal: "20:45",
      status: "Status",
      statusVal: "Delayed",
    },
  },
  knows: {
    eyebrow: "Load #48291, T-1042",
    headline: "Now Zonik knows what happened.",
    status: "Delayed",
    reason: "Reason",
    reasonVal: "Breakdown",
    eta: "New ETA",
    etaVal: "20:45",
    contact: "Last driver contact",
    contactVal: "Just now",
    loop: "Your team now has the information before the broker has to ask.",
    oldTitle: "Old way",
    oldItems: ["Broker calls first.", "Then the team investigates."],
    newTitle: "With Zonik",
    newItems: ["Zonik finds the problem first.", "Then the team can update the broker."],
    payoff: "Be the one giving the update, not the one getting the angry call.",
  },
  paths: {
    headline: "Zonik handles what it can.",
    sub: "Your team handles what needs a human.",
    pathA: {
      title: "Zonik handles it",
      items: [
        "Driver answers",
        "Reason confirmed",
        "New ETA received",
        "Dashboard updated",
        "Tracking continues",
      ],
    },
    pathB: {
      title: "Human needed",
      items: [
        "Driver does not answer",
        "ETA is unknown",
        "Appointment needs to change",
        "Broker or customer needs a decision",
        "Serious operational problem",
      ],
      action: "Dispatcher action: Notify broker",
    },
    footer: ["Zonik handles the tracking task.", "Your team handles the decision."],
  },
  changes: {
    headline: "So what changes for your night team?",
    today: "Today",
    todayItems: [
      "Watch GPS",
      "Open Google Maps",
      "Calculate ETAs",
      "Make check calls",
      "Chase drivers",
      "Update status",
      "Find problems late",
    ],
    withZonik: "With Zonik",
    afterItems: [
      "Handle real exceptions",
      "Talk to brokers when needed",
      "Cover uncovered trucks",
      "Book the next load",
      "Keep trucks moving",
    ],
    payoff: "Less tracking. More dispatching.",
    note: "After hours stops being just a cost center.",
    todayCaption: "The whole night is tracking.",
    afterCaption: "The same people book freight.",
  },
  dispatch: {
    eyebrow: "Why dispatch likes this",
    headline: "Zonik works all day. Dispatch gets time back.",
    points: [
      "Zonik tracks every active load all day and sends status to dispatch.",
      "Dispatchers do not have to check GPS or hunt for ETAs.",
      "Zonik does not call drivers for them. It keeps the board current so they can book freight.",
    ],
    payoff: "Same desk. More freight booked.",
    beforeLabel: "Dispatch today",
    beforeItems: ["Refresh GPS", "Hunt the ETA", "Check the appointment", "Then try to book"],
    afterLabel: "Dispatch with Zonik",
    afterItems: ["Live tracking on the board", "Delay status already there", "Book the next load", "Cover empty trucks"],
  },
  handoff: {
    eyebrow: "Shift change",
    headline: "No more emails between dispatch and after hours.",
    lines: [
      "Today, dispatch writes what after hours should watch.",
      "After hours writes back what happened overnight.",
      "Things get missed. Facts don’t match. The next shift starts guessing.",
    ],
    payoff: "Zonik keeps one board. Both shifts see the same loads, ETAs, calls and exceptions.",
    todayLabel: "Today",
    todayFrom: "Dispatch to after hours",
    todayFromBody: "Please watch T-1042. Chicago at 20:00. Not sure on ETA.",
    todayBack: "After hours to dispatch",
    todayBackBody: "T-1042 was late I think. Driver said breakdown. Need to check in the morning.",
    zonikLabel: "With Zonik",
    zonikBoard: "Same facts. Both shifts.",
    zonikItems: [
      "T-1042 Delayed. Breakdown. ETA 20:45",
      "Driver called just now",
      "No email thread. No “I thought you knew.”",
    ],
  },
  transition: {
    eyebrow: "Now let’s open Zonik",
    headline: "Let me show you what this actually looks like.",
    sub: "We just followed one load. Now let’s look at the whole operation.",
    cta: "Open Live Dashboard",
  },
  integrations: {
    eyebrow: "Optional",
    headline: "Zonik works with the tools you already use.",
    sub: "Your data comes in. Zonik does the work. Updates go back to your team.",
  },
  pricing: {
    eyebrow: "Optional",
    headline: "Pricing built around your operation.",
    sub: "We size Zonik around your fleet and how you actually work.",
    factors: ["Fleet size", "Loads monitored", "AI calling volume", "Number of users"],
    includesTitle: "Every setup includes",
    includes: [
      "24/7 load monitoring",
      "Live ETA and delay detection",
      "Driver calls",
      "Exception alerts",
      "After hours dashboard",
    ],
    note: "We’ll size the right setup together.",
  },
  pilot: {
    eyebrow: "Optional",
    headline: "See Zonik work on your real loads.",
    sub: "Run Zonik alongside your after hours team for 14 days.",
    steps: [
      { title: "Connect", text: "Connect the data needed for the pilot." },
      { title: "Run", text: "Your team works normally. Zonik watches the same loads." },
      {
        title: "Compare",
        text: "See what Zonik caught, who it called, what it resolved, and what needed a human.",
      },
    ],
    cta: "Start a 14 day pilot",
    footer: "Your trucks. Your loads. Your operation.",
  },
  ui: {
    goToSlide: "Go to slide",
  },
} as const;
